1. Membuat kolom baru bernama "Full Name"

In [159]:
import pandas as pd

In [160]:
# Membaca file Excel
excel_file = "Homework-DataFrame-Dataset.xlsx"

In [161]:
# Membaca data dari sheet "Paid-Transaction" dan "Seller"
paid_transaction_df = pd.read_excel(excel_file, sheet_name="Paid-Transaction", header=1)
seller_df = pd.read_excel(excel_file, sheet_name="Seller", header=1)

In [162]:
paid_transaction_df.head()

,Unnamed: 0,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,NaN,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,NaN,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,NaN,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,NaN,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,NaN,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0

In [163]:
paid_transaction_df = paid_transaction_df.iloc[1:,1:]
paid_transaction_df.reset_index(drop=True, inplace = True)
paid_transaction_df.head()

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
1,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
2,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
3,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
4,20170714,201707149671962,fauzannor,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0

In [164]:
paid_transaction_df.dtypes

Paid Date               int64
Order Number            int64
First Name             object
Last Name              object
Meta Category          object
Product Name           object
Transaction Amount      int64
Seller Discount         int64
Sales Discount        float64
Delivery Fee            int64
Other Discount        float64
dtype: object

In [165]:
paid_transaction_df['Paid Date'] = pd.to_datetime(paid_transaction_df['Paid Date'], format='%Y%m%d', errors='ignore')
paid_transaction_df.head()

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,2017-07-01,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
1,2017-07-07,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
2,2017-07-20,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
3,2017-07-22,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
4,2017-07-14,201707149671962,fauzannor,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0

In [166]:
paid_transaction_df.dtypes

Paid Date             datetime64[ns]
Order Number                   int64
First Name                    object
Last Name                     object
Meta Category                 object
Product Name                  object
Transaction Amount             int64
Seller Discount                int64
Sales Discount               float64
Delivery Fee                   int64
Other Discount               float64
dtype: object

In [167]:
seller_df.head()

   Unnamed: 0     Order Number        Seller
0         NaN  201707209929420  Global Phone
1         NaN  201707129550097        E-shop
2         NaN  201707039056021   twelven com
3         NaN  201707099376522      GRAMEDIA
4         NaN  201707028956707        E-Bold

In [168]:
seller_df = seller_df.iloc[1:,1:]
seller_df.reset_index(drop=True, inplace = True)
seller_df.head()

      Order Number       Seller
0  201707129550097       E-shop
1  201707039056021  twelven com
2  201707099376522     GRAMEDIA
3  201707028956707       E-Bold
4  201707240063113       E-Bold

In [169]:
# Menampilkan nama kolom di DataFrame "Paid-Transaction"
print("Columns in 'Paid-Transaction' DataFrame:", paid_transaction_df.columns)

Columns in 'Paid-Transaction' DataFrame: Index(['Paid Date', 'Order Number', 'First Name', 'Last Name', 'Meta Category',
       'Product Name', 'Transaction Amount', 'Seller Discount',
       'Sales Discount', 'Delivery Fee', 'Other Discount'],
      dtype='object')

In [170]:
# Menampilkan nama kolom di DataFrame "Seller"
print("Columns in 'Seller' DataFrame:", seller_df.columns)

Columns in 'Seller' DataFrame: Index(['Order Number', 'Seller'], dtype='object')

In [171]:
# Menggabungkan DataFrame berdasarkan kolom 'Order Number'
merged_df = pd.merge(paid_transaction_df, seller_df, on='Order Number')

In [172]:
# Buat kolom baru "Full Name" dengan format title case
merged_df["Full Name"] = merged_df["First Name"].str.title() + " " + merged_df["Last Name"].str.title()

In [173]:
# Sisipkan kolom "Full Name" setelah kolom "Last Name"
columns = list(merged_df.columns)
last_name_index = columns.index("Last Name")
columns.insert(last_name_index + 1, "Full Name")
merged_df = merged_df.reindex(columns=columns)

In [174]:
# Tampilkan DataFrame hasil
merged_df.head()

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,Seller,Full Name
0,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0,E-Bold,Basir Ninuk
1,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0,XLmystore,Citra Ardi
2,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0,Ennwen Online Store,Dian Renaldi
3,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0,Media Gadget,Rizal Tamba
4,2017-07-14,201707149671962,fauzannor,andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0,E-Bold,Fauzannor Andri

2. Menambahkan Kolom GMV

In [175]:
merged_df["GMV"] = merged_df["Transaction Amount"] - merged_df["Seller Discount"] + merged_df["Delivery Fee"]

In [176]:
# Sisipkan kolom "GMV" setelah kolom "Seller Discount"
columns = list(merged_df.columns)
seller_discount_index = columns.index("Seller Discount")
columns.insert(seller_discount_index + 1, "GMV")
merged_df = merged_df[columns]

In [177]:
# Tampilkan DataFrame hasil
merged_df.head()

,Paid Date,Order Number,First Name,Last Name,Full Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller,Full Name,Full Name,GMV
0,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold,Basir Ninuk,Basir Ninuk,219800
1,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore,Citra Ardi,Citra Ardi,35000
2,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store,Dian Renaldi,Dian Renaldi,85000
3,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget,Rizal Tamba,Rizal Tamba,81000
4,2017-07-14,201707149671962,fauzannor,andri,Fauzannor Andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,E-Bold,Fauzannor Andri,Fauzannor Andri,158000

3. Mengelompokkan setiap Meta Category menjadi 2 group

In [178]:
# Definisikan kategori grup
group_mapping = {
    'Home/Food': 'Group 1',
    'Sports/Hobi/Otomotif': 'Group 1',
    'Fashion': 'Group 1',
    'Beauty/Health': 'Group 1',
    'Gadget/Komputer': 'Group 2',
    'Elektronik': 'Group 2',
    'Service/Mokado': 'Group 2',
    'Babies/Kids': 'Group 2'
}

In [179]:
merged_df["Group"] = merged_df["Meta Category"].map(group_mapping)

<ipython-input-179-79df6349409b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df["Group"] = merged_df["Meta Category"].map(group_mapping)

In [180]:
# Create a pivot table with total GMV per month for each group
merged_df['Paid Date'] = pd.to_datetime(merged_df['Paid Date'])
merged_df['Month'] = merged_df['Paid Date'].dt.to_period('M')

<ipython-input-180-142c87e2a90f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Paid Date'] = pd.to_datetime(merged_df['Paid Date'])
<ipython-input-180-142c87e2a90f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Month'] = merged_df['Paid Date'].dt.to_period('M')

In [181]:
pivot_table = merged_df.pivot_table(
    values='GMV',
    index='Month',
    columns='Group',
    aggfunc='sum',
    fill_value=0
).reset_index()

In [182]:
merged_df.head()

,Paid Date,Order Number,First Name,Last Name,Full Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller,Full Name,Full Name,GMV,Group,Month
0,2017-07-01,201707018889790,BASIR,Ninuk,Basir Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,E-Bold,Basir Ninuk,Basir Ninuk,219800,NaN,2017-07
1,2017-07-07,201707079264675,Citra,Ardi,Citra Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,XLmystore,Citra Ardi,Citra Ardi,35000,NaN,2017-07
2,2017-07-20,201707209945714,Dian,Renaldi,Dian Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Ennwen Online Store,Dian Renaldi,Dian Renaldi,85000,Group 1,2017-07
3,2017-07-22,201707220002354,rizal,Tamba,Rizal Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Media Gadget,Rizal Tamba,Rizal Tamba,81000,NaN,2017-07
4,2017-07-14,201707149671962,fauzannor,andri,Fauzannor Andri,Fauzannor Andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,E-Bold,Fauzannor Andri,Fauzannor Andri,158000,NaN,2017-07

In [183]:
pivot_table

Group    Month    Group 1  Group 2    Group 1  Group 2
0      2017-07   31308700  4089500   31308700  4089500
1      2017-08   15787000  1821800   15787000  1821800
2      2017-09  129389200  6872900  129389200  6872900
3      2017-10   50245600  4979900   50245600  4979900
4      2017-11  144480300  2320500  144480300  2320500
5      2017-12   50632900  3033000   50632900  3033000

4. Membuat python statement untuk mencari Seller yang memiliki total nilai GMV paling tinggi di bulan Agustus 2017

In [194]:
df_august_2017 = merged_df[merged_df['Month'] == '2017-08']
top_seller_august = df_august_2017.groupby('Seller')['GMV'].sum().idxmax()
top_seller_august

GMV    MOBILEPULSA APP
GMV    MOBILEPULSA APP
dtype: object

5. Membuat python statement untuk mencari Seller yang memiliki paling banyak transaksi di bulan September 2017

In [195]:
df_september_2017 = merged_df[(merged_df['Month'] == '2017-09') & (merged_df['Meta Category'] == 'Fashion')]
top_seller_september = df_september_2017['Seller'].value_counts().idxmax()
top_seller_september

'tokoaqila'